// This file provides a client with methods as well as functions to interact with the HTTP API.
//
// Code generated by github.com/MarkRosemaker DO NOT EDIT.

package catfacts

import (
	"context"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/MarkRosemaker/jsonutil"
	"github.com/go-api-libs/api"
	"github.com/go-json-experiment/json"
)

const (
	userAgent = "CatFactsGoAPILibrary/1.0.0 (https://github.com/go-api-libs/cat-facts)"
)

var (
	baseURL = &url.URL{
		Host:   "cat-fact.herokuapp.com",
		Scheme: "https",
	}

	jsonOpts = json.JoinOptions(
		json.RejectUnknownMembers(true),
		json.WithMarshalers(json.NewMarshalers(
			json.MarshalFuncV2(jsonutil.URLMarshal))),
		json.WithUnmarshalers(json.NewUnmarshalers(
			json.UnmarshalFuncV2(jsonutil.URLUnmarshal))))
)

// Client conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The HTTP client to use for requests.
	cli *http.Client
}

// NewClient creates a new Client.
func NewClient() (*Client, error) {
	return &Client{cli: http.DefaultClient}, nil
}

// Get random cat facts
//
//	GET /facts/random
func (c *Client) GetRandom(ctx context.Context, params *GetRandomParams) (Facts, error) {
	return GetRandom[Facts](ctx, c, params)
}

// Get random cat facts
// You can define a custom result to unmarshal the response into.
//
//	GET /facts/random
func GetRandom[R any](ctx context.Context, c *Client, params *GetRandomParams) (R, error) {
	u := baseURL.JoinPath("/facts/random")

	if params != nil {
		q := make(url.Values, 2)

		if params.Amount != 0 {
			q["amount"] = []string{strconv.Itoa(params.Amount)}
		}

		if params.AnimalType != "" {
			q["animal_type"] = []string{params.AnimalType}
		}

		u.RawQuery = q.Encode()
	}

	req := (&http.Request{
		Header:     http.Header{"User-Agent": []string{userAgent}},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	var out R
	rsp, err := c.cli.Do(req)
	if err != nil {
		return out, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// Returns facts
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return out, api.WrapDecodingError(rsp, err)
			}

			return out, nil
		default:
			return out, api.NewErrUnknownContentType(rsp)
		}
	case http.StatusServiceUnavailable:
		// Returns an HTML page reporting an application error
		return out, api.NewErrStatusCode(rsp)
	default:
		return out, api.NewErrUnknownStatusCode(rsp)
	}
}

// GetFactByID defines an operation.
//
//	GET /facts/{id}
func (c *Client) GetFactByID(ctx context.Context, id string) (*GetFactByIDOkJSONResponse, error) {
	return GetFactByID[GetFactByIDOkJSONResponse](ctx, c, id)
}

// GetFactByID defines an operation.
// You can define a custom result to unmarshal the response into.
//
//	GET /facts/{id}
func GetFactByID[R any](ctx context.Context, c *Client, id string) (*R, error) {
	u := baseURL.JoinPath("facts", id)
	req := (&http.Request{
		Header:     http.Header{"User-Agent": []string{userAgent}},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// Returns a fact
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}
