// This file provides a client with methods as well as functions to interact with the HTTP API.
//
// Code generated by github.com/MarkRosemaker DO NOT EDIT.

package catfacts

import (
	"context"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/go-api-libs/api"
	"github.com/go-json-experiment/json"
)

const (
	userAgent = "CatFactsGoAPILibrary/1.0.0 (https://github.com/go-api-libs/cat-facts)"
)

var (
	baseURL = &url.URL{
		Host:   "cat-fact.herokuapp.com",
		Path:   "/facts",
		Scheme: "https",
	}

	jsonOpts = json.JoinOptions(
		json.RejectUnknownMembers(true))
)

// Client conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The HTTP client to use for requests.
	cli *http.Client
}

// NewClient creates a new Client.
func NewClient() (*Client, error) {
	return &Client{cli: http.DefaultClient}, nil
}

// Get random cat facts
//
//	GET /random
func (c *Client) GetRandom(ctx context.Context, params *GetRandomParams) (*GetRandomOkJSONResponse, error) {
	return GetRandom[GetRandomOkJSONResponse](ctx, c, params)
}

// Get random cat facts
// You can define a custom result to unmarshal the response into.
//
//	GET /random
func GetRandom[R any](ctx context.Context, c *Client, params *GetRandomParams) (*R, error) {
	u := baseURL.JoinPath("/random")

	if params != nil && params.Amount != 0 {
		u.RawQuery = url.Values{"amount": []string{strconv.Itoa(params.Amount)}}.Encode()
	}

	req := (&http.Request{
		Header:     http.Header{"User-Agent": []string{userAgent}},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusServiceUnavailable:
		// Returns an HTML page reporting an application error
		return nil, api.NewErrStatusCode(rsp)
	case http.StatusOK:
		// TODO
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}
