// This file provides types for the API.
//
// Code generated by github.com/MarkRosemaker DO NOT EDIT.

package catfacts

import "time"

type GetRandomParams struct {
	// The number of cat facts to return
	Amount int
}

// GetRandomOkJSONResponse defines a model
type GetRandomOkJSONResponse struct {
	Status    Status    `json:"status"`
	ID        string    `json:"_id,omitzero"`
	User      string    `json:"user,omitzero"`
	Text      string    `json:"text,omitzero"`
	Type      string    `json:"type,omitzero"`
	Deleted   bool      `json:"deleted,omitzero"`
	CreatedAt time.Time `json:"createdAt,omitzero"`
	UpdatedAt time.Time `json:"updatedAt,omitzero"`
	V         int       `json:"__v,omitzero"`
}

// Status defines a model
type Status struct {
	Verified  bool `json:"verified,omitzero"`
	SentCount int  `json:"sentCount,omitzero"`
}
