// This file provides types for the API.
//
// Code generated by github.com/MarkRosemaker DO NOT EDIT.

package catfacts

type GetRandomParams struct {
	// The number of cat facts to return
	Amount int
}
